Fix build by resurrecting 'apply_value'
The 'apply_value' function was renamed to 'calc_value', but the
former is still used in 'apply_operation' (commit 7b607b35ee4).
Restore 'apply_value' by delegating to the new 'calc_value'.
This fixes the build by fixing the linker error:
  brightnessctl.c:255: undefined reference to `apply_value'